### ISSUE TITLE
Internal C++ object (PySide2.QtWidgets.QPushButton) already deleted.

### ISSUE THREAD

**Issue by baiyuxiong** [spyder-ide/qtawesome#133]
I and a Spining icon in QWidget subclass:

````
class Icons(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        #.....
        self.spin_button = QtWidgets.QPushButton('Spinning icon')
        self.spin_icon = qta.icon('fa5s.spinner', color='red',
                             animation=qta.Spin(self.spin_button))
        self.spin_button.setProperty("class", "btn btn-outline-primary bt-sm")
        self.spin_button.setIcon(self.spin_icon)
        self.layout.addWidget(self.spin_button)
        #.....
````

Show this dialog in parent window:
````
def showIconDialog(self):
        self.iconDialog = FontAwesome.Icons()
        self.iconDialog.show()
````

While reopen this dialog, I get these error:

````
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/qtawesome/animation.py", line 20, in _update
    self.parent_widget.update()
RuntimeError: Internal C++ object (PySide2.QtWidgets.QPushButton) already deleted.
````

**Comment by darkvertex** [comment]
`super().__init__()` is syntactically invalid. What's your actual `super()` call like?

Remember when creating a QWidget you need to give it a parent widget in the first arg. Otherwise you risk the garbage collector axing your instance, which can cause your "_already deleted_" error.

If your super() is good and passing the `parent=` keyword argument properly, it should work with `FontAwesome.Icons(<parent>)` where `<parent>` is another QWidget, a QDialog or a QApplication for example.

**Comment by goanpeca** [comment]
Closing due to lack of response
