### ISSUE TITLE
Icons are looking bad on Windows 7

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/qtawesome#4]
![image](https://cloud.githubusercontent.com/assets/3627835/6598897/e3920fc0-c806-11e4-8fe2-6b9b3169cfff.png)

**Comment by ccordoba12** [comment]
From the title and text of your screenshot, it seems your Windows version is not using anti-aliasing.

**Comment by goanpeca** [comment]
True! Answer on http://superuser.com/questions/341636/why-windows-7-dialog-fonts-are-not-anti-aliased

![image](https://cloud.githubusercontent.com/assets/3627835/6599655/511ef784-c80b-11e4-9d8a-77f060d157ca.png)

**Comment by SylvainCorlay** [comment]
We should be able to force anti-aliasing with `painter.setRenderHint(QtGui.QPainter.Antialiasing)` in the `paint` method. Will fix this this week-end.

**Comment by goanpeca** [comment]
I tried that. It made no difference. But ley me know

**Comment by SylvainCorlay** [comment]
@ccordoba12 I would like to rename the repository to QtAwesome but am not privileged for that apparently. (see gitter messages)

**Comment by goanpeca** [comment]
Ok so it seems that when TrueType is enabled in windows, qtawesome results in aliased icons. This is unexpected, because apparently qt should use trutype if enabled...

**Comment by SylvainCorlay** [comment]
I also tried using `font.setStyleStrategy(QFont.PreferAntialias)` but no luck so far.

**Comment by goanpeca** [comment]
@SylvainCorlay, yep I had tried that one as well, but it is a weird "bug" from qt I think. Still even at pixel perfect if no antialias is in place icons will look pixelated like an 80's game :-)

**Comment by SylvainCorlay** [comment]
Actually at pixel perfect size, it is difficult to see the difference .The problem remains for brand icons and such, (like the Python logo) which are not meant to be pixel perfect.

**Comment by SylvainCorlay** [comment]
@ccordoba12 I had some questions on gitter regarding your qt build on windows.

**Comment by ccordoba12** [comment]
We don't build Qt on Windows. We just the binaries supplied by Riverbank (the company behind PyQt)

**Comment by SylvainCorlay** [comment]
It seems that their binaries is not configured with directwrite on Windows 7. 

See: http://pyqt.sourceforge.net/Docs/PyQt4/qfont.html

*Please be aware that altering the hinting preference on Windows is available through the DirectWrite font engine. This is available on Windows Vista after installing the platform update, and on Windows 7. In order to use this extension, configure Qt using -directwrite. The target application will then depend on the availability of DirectWrite on the target system.*

**Comment by ccordoba12** [comment]
Then what do we (i.e. Continuum) should do about it? Should we ask Riverbank for that option?

**Comment by SylvainCorlay** [comment]
It seems that directwrite was intended to replace GDI and should probably be the preferred way of rendering fonts on screen. Although I should make some more experiments with my own build to be able to make an educated recommendation. The problem is that I don't use windows too often and my development machine is a Linux one.

@kovidgoyal replied to my email on the PyQt mailing list with some pointers at where to look

A few observations though:
- even with `ClearType`  and `Smooth edges` enabled (which is the default on all the machines I used, the fonts don't look quite as sharp as on linux, where is it nearly perfect.)
- At pixel perfect size of the font, the problem is much less visible. There are some options in how text is rendered to try using certain preferred sizes.

**Comment by ccordoba12** [comment]
Ok, let me know what you find to see what we can do about it in our side :-)

**Comment by SylvainCorlay** [comment]
Btw, there is also the `FreeType` font engine, which is used on linux, and can (apparently) be used for a windows build. 
If one gets a build of qt where directwrite (or freetype) is enabled, it will support setting up hinting with `QFont.setHintingPreference`, and we will be able to choose what we prefer. 


 | PreferDefaultHinting  | PreferNoHinting | PreferVerticalHinting | PreferFullHinting
---------------------- | ------------- | ------------- | ------------- | -------------
Win Vista (w/o Platform Update) and earlier |	Full hinting | Full hinting | Full hinting | Full hinting
Win 7 and Win Vista (w/Platform Update) and DirectWrite enabled in Qt | Full hinting | Vertical hinting | Vertical hinting | Full hinting
FreeType	| Operating System setting | No hinting | Vertical hinting (light) | Full hinting
Cocoa on Mac OS X | No hinting | No hinting | No hinting | No hinting

**Comment by SylvainCorlay** [comment]
@ccordoba12 you guys now ship freetype with Anaconda?

**Comment by ccordoba12** [comment]
Yes, I think we have it available on all platforms. I'm totally sure on Linux and Mac, but not so sure on Windows :-)

**Comment by goanpeca** [comment]
Should we close this @ccordoba12 ?

**Comment by ccordoba12** [comment]
Sure, let's do it.
