### ISSUE TITLE
qtpy & Qt.py

### ISSUE THREAD

**Issue by SylvainCorlay** [spyder-ide/qtawesome#74]
I have been contacted on other channels by users of [Qt.py](https://github.com/mottosso/Qt.py) who would like qtawesome to also work with it instead of qtpy only.

**Comment by ccordoba12** [comment]
I don't know about this. How could we handle it here? By creating a shim for Qt shims?

**Comment by SylvainCorlay** [comment]
A shim to rule all the shims!

**Comment by ccordoba12** [comment]
We asked Qt.py people to merge their work with qtpy, but they declined. So I'd say I'm -1 on this.

**Comment by SylvainCorlay** [comment]
OK, I did not know. At least we have a trace on this!

**Comment by nrusch** [comment]
I know this is in an old issue, but I just want to mention that the hard dependency on `qtpy` causes actual runtime problems because its patching breaks various built-in enum type functionality in PySide6. For instance, it prevents `QtCore.Qt.ItemFlags` from being used in a union type annotation without forward referencing the whole expression because the `Enum` type is replaced... with a `lambda`.

The most unfortunate part is that it patches the forwarded API in place, rather than providing its own proxy ~modules~ symbols (as `Qt.py` does), so it's extremely invasive (it doesn't play well with others). As users of both `qtawesome` and `Qt.py`, our only real recourse is to fork and patch `qtawesome` to remove the hardcoded `qtpy` dependency.
